version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=zeetcode
      - POSTGRES_USER=zeetcode
      - POSTGRES_DB=zeetcode
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
